name: Update S3 Bucket and Invalidate CDN Cache
on:
  push:
    branches:
      - "main"
jobs:
  Deploy-S3-Bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
      - uses: actions/checkout@v4
      - run: echo "The ${{github.repository}} has been cloned"

      - name: Check for AWS Cli installation in runner.
      - run: aws configure
