name: Deploy to S3 and Invalidate CloudFront Cache

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check AWS Cli version
        run: aws --version
      - name: Deploy to S3
        run: |
          aws s3 sync . s3://s3-thecatlounge-v1/ --delete

      - name: Refresh Cloudfront Cache
        run: |
          aws cloudfront create-invalidation --distribution-id E2ROYF6OZK3G3R --paths /*
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
